name: Publish and commit bottles

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        required: true
      args:
        description: "Extra arguments to `brew pr-pull`"
        default: ""

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Post comment once started
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{github.token}}
          issue: ${{github.event.inputs.pull_request}}
          body: ":shipit: @${{github.actor}} has [triggered a merge](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}})."
          bot_body: ":robot: A scheduled task has [triggered a merge](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}})."
      
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Unlink workspace
        run: |
          mv "${GITHUB_WORKSPACE}" "${GITHUB_WORKSPACE}-link"
          mkdir "${GITHUB_WORKSPACE}"
      
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: ${{steps.set-up-homebrew.outputs.gems-path}}
          key: ${{runner.os}}-rubygems-v2-${{steps.set-up-homebrew.outputs.gems-hash}}
          restore-keys: ${{runner.os}}-rubygems-v2-
      
      - name: Re-link workspace
        run: |
          rmdir "${GITHUB_WORKSPACE}"
          mv "${GITHUB_WORKSPACE}-link" "${GITHUB_WORKSPACE}"

      - name: Install gems
        run: brew install-bundler-gems

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Pull and upload bottles to GitHub Packages
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{github.token}}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{github.repository_owner}}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{secrets.HOMEBREW_GITHUB_PACKAGES_TOKEN}}
        run: |
          brew pr-pull --tap=$GITHUB_REPOSITORY --root-url="https://ghcr.io/v2/${{github.repository_owner}}/taps" ${{github.event.inputs.args}} ${{github.event.inputs.pull_request}}

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{github.token}}
          branch: main
      
      - name: Post comment on failure
        if: ${{!success()}}
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{github.token}}
          issue: ${{github.event.inputs.pull_request}}
          body: ":warning: @${{github.actor}} bottle publish [failed](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}})."
          bot_body: ":warning: Bottle publish [failed](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}})."

      - name: Unlink workspace
        run: |
          rm "${GITHUB_WORKSPACE}"
          mkdir "${GITHUB_WORKSPACE}"
